name: carb
channels:
  - conda-forge
dependencies:
  - python=3.9
  - aiohttp=3.8.4
  - bokeh=3.2.0
  - dask=2023.4.0
  - dask-labextension=7.0.0
  - geopandas=0.14.1
  - holoviews=1.18.1
  - hvplot=0.9.0
  - ipywidgets=8.0.7
  - jupyter-server-proxy=4.0.0
  - jupyterhub-singleuser=4.0.2
  - jupyterlab=4.0.9
  - nbgitpuller=1.1.1
  - netcdf4=1.6.4
  - notebook=6.4.12
  - openpyxl=3.1.2
  - pip
  - pandas=2.0.3
  - panel=1.2.3
  - param=1.13.0
  - proj=9.2.1 
  - pyproj=3.6.0 
  - requests=2.31.0
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - statsmodels=0.14.0
  - tqdm=4.65.0
  - xarray=2023.7.0
  - xclim=0.46.0
  - zarr=2.15.0
